# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.0+26.1.1
group=cc.avie.esad

# Dependencies
fabric_api_version=0.145.4+26.1.1

# TabbyLib (https://avie.cc/wiki/tabbylib/)
tabbylib_version=1.0.0+26.1.1
